### ISSUE TITLE
 Le lien du CTA dans le header ne s'ouvre pas dans un nouvel onglet (alors que c'est un lien externe)

### ISSUE THREAD

**Issue by MagaliAngles** [osunyorg/futurs-site#4]
Sur la page d'accueil (https://www.futurs-lejeu.fr/fr/), le premier CTA "je commande" renvoi vers un lien externe et il s'ouvre dans le même onglet.
Dans l'admin, il n'y a pas de possibilité de prévoir un lien externe, on peut juste rentrer une url.

<img width="832" alt="Capture d’écran 2024-09-17 à 15 44 38" src="https://github.com/user-attachments/assets/53f6598b-ae9f-4abb-8d0a-829e30732954">

**Comment by Olivia206** [comment]
J'ai fait une issue dans l'admin : https://github.com/osunyorg/admin/issues/2283
