### ISSUE TITLE
Footer  : Contact - Commander FUTURs : il manque le picto indiquant que lien s'ouvre dans un nouvel onglet

### ISSUE THREAD

**Issue by MagaliAngles** [osunyorg/futurs-site#5]
Dans le footer, il manque le picto indiquant que lien s'ouvre dans un nouvel onglet (c'est bien le cas il s'ouvre dans un nouvel onglet)
<img width="377" alt="Capture d’écran 2024-09-17 à 16 33 12" src="https://github.com/user-attachments/assets/54b521e9-c4ad-421a-a2f7-9f2264a44b2b">

**Comment by Olivia206** [comment]
C'est une de leur demande
